name: Build Kernel

on:
  workflow_dispatch:
    inputs:
      device:
        description: 'device codename'
        required: true
        default: 'topaz'

      repo:
        description: 'Kernel source link'
        required: true

      branch:
        description: 'Kernel source branch'
        required: true
        default: 'main'

env:
  TZ: Asia/Jakarta
  DEVICE: ${{ github.event.inputs.device }}
  REPO: ${{ github.event.inputs.repo }}
  BRANCH: ${{ github.event.inputs.branch }}

  token: ${{ secrets.TG_TOKEN }}
  chat_id: ${{ secrets.TG_CHAT_ID }}

jobs:
  kernel-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Initializing environment
        run: |
          sudo apt update

          sudo apt install -y \
          bc bison build-essential ccache curl flex g++-multilib \
          gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev \
          lib32readline-dev lib32z1-dev liblz4-tool libncurses5 \
          libncurses5-dev libsdl1.2-dev libssl-dev libxml2 \
          libxml2-utils lzop pngcrush rsync schedtool squashfs-tools \
          xsltproc zip zlib1g-dev python2 neofetch repo

          git config --global user.name "neophyte404"
          git config --global user.email "260553983+neophyte404@users.noreply.github.com"

          neofetch

      - name: Run build script
        run: |
          wget https://raw.githubusercontent.com/neophyte404/kernel_build/main/topaz.sh
          chmod +x topaz.sh
          bash topaz.sh
